name: Publish InfraWeave Module

on:
  workflow_call:
    inputs:
      central_account_id:
        description: 'AWS Account ID'
        required: true
        type: string
      environment:
        description: 'InfraWeave environment (e.g., dev, prod)'
        required: true
        type: string
      version:
        description: 'Version to publish'
        required: true
        type: string
      region:
        description: 'Region to use (default is us-west-2)'
        required: false
        type: string
        default: us-west-2


jobs:
  extract-version:
    uses: ./.github/workflows/version.yaml
    with:
      tag: ${{ inputs.version }}

  publish:
    runs-on: ubuntu-latest
    needs: extract-version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ inputs.central_account_id }}:role/infraweave-oidc-role-${{ inputs.environment }}
          aws-region: ${{ inputs.region }}

      - name: Publish module to InfraWeave
        run: |
          curl -L -o infraweave https://github.com/infraweave-io/infraweave/releases/download/v0.0.76/cli-linux-amd64
          chmod +x infraweave
          sudo mv infraweave /usr/local/bin
          infraweave module publish ${{ needs.extract-version.outputs.track }} ./src --version "${{ inputs.version }}"
